### ISSUE TITLE
About preparing depth labels

### ISSUE THREAD

**Issue by PSYZ1234** [maggiesong7/SDTR#1]
Hi, thank you for your good paper and code. 

I am trying to generate depth labels, but I encountered an issue where the system prompts that the nuscenes_12hz_infos_train.pkl file is unavailable. Could you please clarify how this .pkl file is generated? I was unable to produce this file during the previous preparation steps.

Additionally, I attempted to replace nuscenes_12hz_infos_train.pkl with my own nuscenes_infos_train.pkl, but I still couldn't generate the depth labels. The depth folder remains empty. Could you advise on how to resolve this issue?

**Comment by maggiesong7** [comment]
Hi, I have uploaded the _nuscenes_12hz_infos_train.pkl_ file and you can download it from [gdrive](https://drive.google.com/drive/folders/1GgejgKFEKJw_ppPTBSfPBAjesDDBB3oP?usp=sharing).

**Comment by PSYZ1234** [comment]
Thank you!
